"""Where an asset physically lives (ADR-0024).

Asset paths like ``chant/ant/laetare.gabc`` or ``images/03-lambert/foo.jpg`` are
*logical*: they are what the rendered TeX reads (``\\gregorioscore{chant/…}``),
what a staged build folder reproduces under those same names, and what the
form's data island offers. Those never change.

What ADR-0024 changed is only where each logical path is *read from*. Three
providers, distinguished by the logical path itself:

**Bundled** — ships inside the installed package: the chant library, the
per-ordo skeletons, the psalm-tone engine, and the gilded border tiles. These
are the tool, not the user's data, and an installed wheel must carry them.

**Generated** — written at build time (inline gabc blocks materialised from a
feast spec, decoded ``data:`` images, and the per-tone verse cache). These keep
their logical ``chant/…`` and ``images/…`` names so the staged folder and the
TeX stay unchanged, but they must never be written into the package, which in a
normal install lives in a read-only ``site-packages``. They go under
``build/.cache/`` in the working directory instead.

**Content** — everything else: feast specs, per-feast pictures, and the
Psalter. Supplied by whoever is making the booklet, read from the working
directory.
"""

from __future__ import annotations

from pathlib import Path

#: The installed package directory — the root of every bundled asset.
PACKAGE_ROOT = Path(__file__).parent

#: Logical prefixes served by the package rather than the working directory.
#: Order does not matter; these must not overlap with the generated dirs below.
BUNDLED_PREFIXES = (
    "chant",
    "template",
    "psalm-library",
    # Ornaments, not pictures of anything: the gilded border tiles and the
    # drolleries are part of the booklet's decoration, so they belong to the
    # tool. Per-feast photographs under images/<feast>/ are content.
    "images/borders",
    "images/drollery",
)

#: A path component with this name marks generated output, at any depth:
#: ``chant/inline/…``, ``chant/psalmi/109/toni/8gstar/…``, ``images/inline/…``.
#: Deliberately excludes ``kurzfassung`` — the committed two-verse Magnificat
#: systems (ADR-0022) are generated by a maintainer command and then reviewed
#: and committed, so they are bundled assets like any other gabc file.
GENERATED_DIR_NAMES = frozenset({"inline", "toni"})

#: Generated assets are written here, relative to the working directory. Under
#: build/ so that `libellus`' existing build output remains the one place a
#: build writes to, and so a stale cache is cleared by removing build/.
CACHE_PREFIX = Path("build/.cache")


def is_generated(asset: Path) -> bool:
    """Whether this logical path is build-time output rather than a stored file."""
    return bool(GENERATED_DIR_NAMES.intersection(asset.parts))


def is_bundled(asset: Path) -> bool:
    """Whether this logical path is served by the installed package."""
    if is_generated(asset):
        return False
    posix = asset.as_posix()
    return any(
        posix == prefix or posix.startswith(f"{prefix}/")
        for prefix in BUNDLED_PREFIXES
    )


def source_of(asset: Path, content_root: Path) -> Path:
    """The physical file to read for a logical asset path.

    :param asset: Logical, staging-relative path, e.g. ``chant/ant/x.gabc``.
    :param content_root: The working directory a build runs in.
    """
    if is_generated(asset):
        return content_root / CACHE_PREFIX / asset
    if is_bundled(asset):
        return PACKAGE_ROOT / asset
    return content_root / asset


def bundled(*parts: str) -> Path:
    """A path inside the package, for reads that are not staged assets."""
    return PACKAGE_ROOT.joinpath(*parts)
