"""Stage a self-contained build folder: rendered TeX + assets + Makefile.

The folder needs neither libellus nor the repository — running ``make``
inside it (lualatex with gregoriotex, pdfjam, pdftk) produces the booklet
PDFs. This is the unit a Docker build job will consume. Asset paths are
copied under their logical names, unchanged, because the rendered TeX
references them that way (``\\gregorioscore{chant/...}``) — but those names no
longer say where the file is *read* from: the chant library comes from the
installed package and generated notation from ``build/.cache/``. See
:mod:`libellus.paths`.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path

from libellus.paths import source_of

logger = logging.getLogger(__name__)

#: `make` in the staged folder = the proven compile loop + imposition.
#: Mirrors _lualatex()/impose() in libellus.compile — keep the two in sync.
_MAKEFILE_BODY = """
all: $(STEM)-pdfjam-duplex.pdf

$(STEM).pdf: $(STEM).tex
	# gregoriotex autocompile can garble one source line per run; rerun
	# until the log has no errors (max 4 passes), then one settling pass
	for i in 1 2 3 4; do \\
	  lualatex --shell-escape --interaction=nonstopmode $(STEM).tex; \\
	  grep -q '^!' $(STEM).log || break; \\
	done
	@grep -q '^!' $(STEM).log && { echo "LaTeX errors remain after 4 passes"; exit 1; } || true
	lualatex --shell-escape --interaction=nonstopmode $(STEM).tex

$(STEM)-pdfjam.pdf: $(STEM).pdf
	pdfjam --booklet true --landscape --paper a4paper $(STEM).pdf -o $(STEM)-pdfjam.pdf

# duplex printers without a binding-edge option flip the back side upside
# down; rotate every second page 180 degrees to compensate
$(STEM)-pdfjam-duplex.pdf: $(STEM)-pdfjam.pdf
	pdftk $(STEM)-pdfjam.pdf rotate 1-endevensouth output $(STEM)-pdfjam-duplex.pdf

clean:
	rm -rf *.pdf *.aux *.log *.gaux *.gtex tmp-gre/

.PHONY: all clean
"""


def stage(
    tex_source: str, assets: list[Path], stem: str, root: Path, build_dir: Path
) -> Path:
    """Write ``<stem>.tex`` + Makefile into ``build_dir`` and copy all assets.

    :param tex_source: The fully rendered LaTeX source.
    :param assets: Logical paths of the files the TeX reads at compile time;
        reproduced under these same names inside ``build_dir``.
    :param stem: Basename for the .tex/.pdf files (usually the feast slug).
    :param root: The working directory; bundled and generated assets are
        resolved relative to the package and the cache instead.
    :param build_dir: Target folder; wiped first if it already exists.
    :return: ``build_dir``.
    """
    if build_dir.exists():
        logger.info("Räume alten Satzordner „%s“ ab.", build_dir)
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True)

    tex_file = build_dir / f"{stem}.tex"
    tex_file.write_text(tex_source, encoding="utf-8")
    logger.debug("Geschrieben: %s (%d Zeichen).", tex_file.name, len(tex_source))

    total_bytes = 0
    for asset in sorted(set(assets)):
        source = source_of(asset, root)
        target = build_dir / asset
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        size = source.stat().st_size
        total_bytes += size
        logger.debug("Kopiert: %s (%d Bytes).", asset, size)

    makefile = f"# Generated by libellus — `make` builds the booklet PDFs.\nSTEM := {stem}\n{_MAKEFILE_BODY}"
    (build_dir / "Makefile").write_text(makefile, encoding="utf-8")

    logger.info(
        "Satzordner fertig: „%s“ (%d Anlagen, %.1f MB).",
        build_dir, len(set(assets)), total_bytes / 1_000_000,
    )
    return build_dir
